#!/system/bin/sh
exec 2>/dev/null
if [ "$(getprop debug.core.policy.runtime)" = "done" ]; then
    exit 0
fi
write(){
    local path="$1"
    local value="$2"
    [ -e "$path" ] && echo "$value" > "$path"
}
write /dev/cpuctl/restricted/cpu.uclamp.min 0
write /dev/cpuctl/restricted/cpu.uclamp.max 3
write /dev/cpuctl/restricted/cpu.uclamp.latency_sensitive 0
write /dev/cpuctl/restricted/cpu.shares 16

write /dev/cpuctl/background/cpu.uclamp.min 0
write /dev/cpuctl/background/cpu.uclamp.max 5
write /dev/cpuctl/background/cpu.uclamp.latency_sensitive 0
write /dev/cpuctl/background/cpu.shares 32

write /dev/cpuctl/system-background/cpu.uclamp.min 0
write /dev/cpuctl/system-background/cpu.uclamp.max 15
write /dev/cpuctl/system-background/cpu.uclamp.latency_sensitive 0
write /dev/cpuctl/system-background/cpu.shares 128

write /dev/cpuctl/foreground/cpu.uclamp.min 0
write /dev/cpuctl/foreground/cpu.uclamp.max 25
write /dev/cpuctl/foreground/cpu.uclamp.latency_sensitive 0
write /dev/cpuctl/foreground/cpu.shares 256

write /dev/cpuset/restricted/cpus 0-3
write /dev/cpuset/restricted/mems 0
write /dev/cpuset/restricted/sched_load_balance 0

write /dev/cpuset/background/cpus 0-3
write /dev/cpuset/background/mems 0
write /dev/cpuset/background/sched_load_balance 0

write /dev/cpuset/system-background/cpus 0-3
write /dev/cpuset/system-background/mems 0
write /dev/cpuset/system-background/sched_load_balance 0

write /dev/cpuset/foreground/cpus 0-5
write /dev/cpuset/foreground/mems 0
write /dev/cpuset/foreground/sched_load_balance 1

write /proc/sys/vm/swappiness 15
write /proc/sys/vm/watermark_scale_factor 10
write /proc/sys/vm/vfs_cache_pressure 100
write /proc/sys/vm/page-cluster 0

write /proc/sys/vm/dirty_ratio 10
write /proc/sys/vm/dirty_background_ratio 5

write /proc/sys/vm/overcommit_memory 1
write /proc/sys/vm/overcommit_ratio 50

write /proc/sys/vm/dirty_expire_centisecs 1500
write /proc/sys/vm/dirty_writeback_centisecs 500

write /proc/sys/vm/compaction_proactiveness 1
write /proc/sys/vm/extfrag_threshold 100

write /proc/sys/vm/min_free_kbytes 4056
write /proc/sys/vm/stat_interval 10

write /sys/block/zram0/max_comp_streams 1
write /sys/block/zram0/writeback_limit_enable 0

write /proc/sys/vm/zone_reclaim_mode 0
write /sys/kernel/mm/transparent_hugepage/enabled never
write /sys/kernel/mm/transparent_hugepage/defrag never

write /proc/sys/kernel/sched_migration_cost_ns 5000000
write /proc/sys/kernel/sched_latency_ns 6000000
write /proc/sys/kernel/sched_min_granularity_ns 750000
write /proc/sys/kernel/sched_wakeup_granularity_ns 1000000

for dev in sda sdb sdc; do
    write "/sys/block/$dev/queue/scheduler" "mq-deadline"
    write "/sys/block/$dev/queue/read_ahead_kb" "128"
    write "/sys/block/$dev/queue/iostats" 0
    write "/sys/block/$dev/queue/nr_requests" 64
done

CMD=/system/bin/cmd
PROTECT_PKGS="
android
com.android.systemui
com.android.providers.telephony
com.android.providers.media
com.android.providers.settings
com.android.bluetooth
com.android.settings
com.android.launcher3
com.android.permissioncontroller
com.google.android.gms
com.google.android.gsf
"
for pkg in $($CMD package list packages -s | sed 's/package://'); do
    case " $PROTECT_PKGS " in
        *" $pkg "*) continue ;;
    esac

    $CMD activity make-uid-idle --user 0 "$pkg"
    $CMD sensorservice set-uid-state "$pkg" idle
done

setprop debug.core.policy.runtime done
